apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: false
    basicAuth: false
    jsonData:
      timeInterval: "15s"
      httpMethod: GET
