name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: make install

    - name: Run linting
      run: make lint

  test-servicekit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: make install

    - name: Test servicekit
      run: make test-servicekit

    - name: Upload servicekit coverage
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: servicekit
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}

  test-chapkit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: make install

    - name: Test chapkit
      run: make test-chapkit

    - name: Upload chapkit coverage
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: chapkit
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
